In [1]:
import numpy as np
import pandas as pd

Question.1
Import pandas and read in the banklist.csv file into a dataframe called
banks.

In [2]:
#Question 1
data = pd.read_csv("/content/banklist.csv")
data

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
...,...,...,...,...,...,...,...
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,19-Aug-14
549,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,18-Nov-02
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,18-Feb-03
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,17-Mar-05
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,17-Mar-05

Question 2.Show the head of the dataframe

In [3]:
#Question2
data.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

Question.3 What are the column names?

In [4]:
#Question3
data.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

Question.4 How many States (ST) are represented in this data set?

In [5]:
#Question4
data["ST"].nunique()

44

Question.5 Get a list or array of all the states in the data set.

In [6]:
#Question5
data["ST"].unique()

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

Question.6 What are the top 5 states with the most failed banks?

In [7]:
#Questio6
data.groupby(("ST"))["CERT"].sum().sort_values().head()

ST
WV     6782
HI    21029
WY    22754
MA    26619
MS    30087
Name: CERT, dtype: int64

Question.7  What are the top 5 acquiring institutions?

In [8]:
#Question7
data.groupby(("Acquiring Institution"))["Bank Name"].count().sort_values(ascending= False).head(5)

Acquiring Institution
No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: Bank Name, dtype: int64

Question.8 How many banks has the State Bank of Texas acquired? How many of them were actually in Texas?

In [9]:
#Question8
a= data[data["Acquiring Institution"] == "State Bank of Texas"]
print("Those banks has acquired state bank of texas:",len(a))
g = data[(data["Acquiring Institution"] == "State Bank of Texas") & (data["ST"] == "TX")]
d = len(g)
print("Those banks were actully in Texas:",d)

Those banks has acquired state bank of texas: 3
Those banks were actully in Texas: 1

Question.9 What is the most common city in California for a bank to fail in?

In [10]:
#Question9
data[(data["CERT"].sort_values(ascending=True)) & (data["ST"] == "CA")]

<ipython-input-10-13e2fae68cbb>:2: FutureWarning: Operation between non boolean Series with different indexes will no longer return a boolean result in a future version. Cast both Series to object type to maintain the prior behavior.
  data[(data["CERT"].sort_values(ascending=True)) & (data["ST"] == "CA")]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
131,Citizens Bank of Northern California,Nevada City,CA,33983,Tri Counties Bank,23-Sep-11,9-Oct-12
182,"San Luis Trust Bank, FSB",San Luis Obispo,CA,34783,First California Bank,18-Feb-11,12-Sep-16
183,Charter Oak Bank,Napa,CA,57855,Bank of Marin,18-Feb-11,12-Sep-12
218,First Vietnamese American Bank,Westminster,CA,57885,Grandpoint Bank,5-Nov-10,12-Sep-12
220,Western Commercial Bank,Woodland Hills,CA,58087,First California Bank,5-Nov-10,12-Sep-16
243,Sonoma Valley Bank,Sonoma,CA,27259,Westamerica Bank,20-Aug-10,12-Sep-12
244,Los Padres Bank,Solvang,CA,32165,Pacific Western Bank,20-Aug-10,12-Sep-12
245,Butte Community Bank,Chico,CA,33219,"Rabobank, N.A.",20-Aug-10,12-Sep-12
284,"Granite Community Bank, NA",Granite Bay,CA,57315,Tri Counties Bank,28-May-10,14-Sep-12
293,1st Pacific Bank of California,San Diego,CA,35517,City National Bank,7-May-10,13-Dec-12
312,Tamalpais Bank,San Rafael,CA,33493,"Union Bank, N.A.",16-Apr-10,23-Aug-12
341,"La Jolla Bank, FSB",La Jolla,CA,32423,"OneWest Bank, FSB",19-Feb-10,24-Aug-12
347,First Regional Bank,Los Angeles,CA,23011,First-Citizens Bank & Trust Company,29-Jan-10,4-Mar-16
381,United Commercial Bank,San Francisco,CA,32469,East West Bank,6-Nov-09,5-Nov-12
391,California National Bank,Los Angeles,CA,34659,U.S. Bank N.A.,30-Oct-09,5-Sep-12
417,Affinity Bank,Ventura,CA,27197,Pacific Western Bank,28-Aug-09,21-Aug-12
444,Temecula Valley Bank,Temecula,CA,34341,First-Citizens Bank & Trust Company,17-Jul-09,20-Oct-16
457,MetroPacific Bank,Irvine,CA,57893,Sunwest Bank,26-Jun-09,5-Feb-15
473,First Bank of Beverly Hills,Calabasas,CA,32069,No Acquirer,24-Apr-09,4-Sep-12
498,1st Centennial Bank,Redlands,CA,33025,First California Bank,23-Jan-09,13-Apr-16
507,Security Pacific Bank,Los Angeles,CA,23595,Pacific Western Bank,7-Nov-08,28-Aug-12
519,"First Heritage Bank, NA",Newport Beach,CA,57961,Mutual of Omaha Bank,25-Jul-08,12-Sep-16